name: ArtemisMafia
main: com.theartemismc.Mafia.Mafia
version: 0.01
commands:
   mafiaadmin:
      description: Admin command for Mafia
      usage: /<command>
   mafia:
      description: Command for help and evil actions in mafia
      usage: /<command>
   town:
      description: Command for town actions in mafia
      usage: /<command>
permissions:
  mafia.*:
    description: Permission to give access to all commands
    children:
      mafia.admin
      mafia.start
  mafia.admin:
    description: Permission to give access set-up commands
  mafia.start:
    description: Permission to start/stop game
    